/*
 Bootstrap v3.3.7 (http://getbootstrap.com)
 Copyright 2011-2018 Twitter, Inc.
 Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
 Generated using the Bootstrap Customizer (<none>)
 Config saved to config.json and <none>
*/
if("undefined"===typeof jQuery)throw Error("Bootstrap's JavaScript requires jQuery");+function(b){b=b.fn.jquery.split(" ")[0].split(".");if(2>b[0]&&9>b[1]||1==b[0]&&9==b[1]&&1>b[2]||3<b[0])throw Error("Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4");}(jQuery);
+function(b){function h(a){var c=a.attr("data-target");c||(c=(c=a.attr("href"))&&/#[A-Za-z]/.test(c)&&c.replace(/.*(?=#[^\s]*$)/,""));return(c=c&&b(c))&&c.length?c:a.parent()}function f(a){a&&3===a.which||(b(".dropdown-backdrop").remove(),b('[data-toggle="dropdown"]').each(function(){var c=b(this),d=h(c),e={relatedTarget:this};!d.hasClass("open")||a&&"click"==a.type&&/input|textarea/i.test(a.target.tagName)&&b.contains(d[0],a.target)||(d.trigger(a=b.Event("hide.bs.dropdown",e)),a.isDefaultPrevented()||
(c.attr("aria-expanded","false"),d.removeClass("open").trigger(b.Event("hidden.bs.dropdown",e))))}))}var e=function(a){b(a).on("click.bs.dropdown",this.toggle)};e.VERSION="3.3.7";e.prototype.toggle=function(a){var c=b(this);if(!c.is(".disabled, :disabled")){var d=h(c);a=d.hasClass("open");f();if(!a){if("ontouchstart"in document.documentElement&&!d.closest(".navbar-nav").length)b(document.createElement("div")).addClass("dropdown-backdrop").insertAfter(b(this)).on("click",f);var e={relatedTarget:this};
d.trigger(a=b.Event("show.bs.dropdown",e));if(a.isDefaultPrevented())return;c.trigger("focus").attr("aria-expanded","true");d.toggleClass("open").trigger(b.Event("shown.bs.dropdown",e))}return!1}};e.prototype.keydown=function(a){if(/(38|40|27|32)/.test(a.which)&&!/input|textarea/i.test(a.target.tagName)){var c=b(this);a.preventDefault();a.stopPropagation();if(!c.is(".disabled, :disabled")){var d=h(c),e=d.hasClass("open");if(!e&&27!=a.which||e&&27==a.which)return 27==a.which&&d.find('[data-toggle="dropdown"]').trigger("focus"),
c.trigger("click");c=d.find(".dropdown-menu li:not(.disabled):visible a");c.length&&(d=c.index(a.target),38==a.which&&0<d&&d--,40==a.which&&d<c.length-1&&d++,~d||(d=0),c.eq(d).trigger("focus"))}}};var g=b.fn.dropdown;b.fn.dropdown=function(a){return this.each(function(){var c=b(this),d=c.data("bs.dropdown");d||c.data("bs.dropdown",d=new e(this));"string"==typeof a&&d[a].call(c)})};b.fn.dropdown.Constructor=e;b.fn.dropdown.noConflict=function(){b.fn.dropdown=g;return this};b(document).on("click.bs.dropdown.data-api",
f).on("click.bs.dropdown.data-api",".dropdown form",function(a){a.stopPropagation()}).on("click.bs.dropdown.data-api",'[data-toggle="dropdown"]',e.prototype.toggle).on("keydown.bs.dropdown.data-api",'[data-toggle="dropdown"]',e.prototype.keydown).on("keydown.bs.dropdown.data-api",".dropdown-menu",e.prototype.keydown)}(jQuery);
+function(b){function h(a){return this.each(function(){var c=b(this),d=c.data("bs.tab");d||c.data("bs.tab",d=new f(this));if("string"==typeof a)d[a]()})}var f=function(a){this.element=b(a)};f.VERSION="3.3.7";f.TRANSITION_DURATION=150;f.prototype.show=function(){var a=this.element,c=a.closest("ul:not(.dropdown-menu)"),d=a.data("target");d||(d=(d=a.attr("href"))&&d.replace(/.*(?=#[^\s]*$)/,""));if(!a.parent("li").hasClass("active")){var e=c.find(".active:last a"),f=b.Event("hide.bs.tab",{relatedTarget:a[0]}),
g=b.Event("show.bs.tab",{relatedTarget:e[0]});e.trigger(f);a.trigger(g);g.isDefaultPrevented()||f.isDefaultPrevented()||(d=b(d),this.activate(a.closest("li"),c),this.activate(d,d.parent(),function(){e.trigger({type:"hidden.bs.tab",relatedTarget:a[0]});a.trigger({type:"shown.bs.tab",relatedTarget:e[0]})}))}};f.prototype.activate=function(a,c,d){function e(){g.removeClass("active").find("> .dropdown-menu > .active").removeClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!1);a.addClass("active").find('[data-toggle="tab"]').attr("aria-expanded",
!0);h?(a[0].offsetWidth,a.addClass("in")):a.removeClass("fade");a.parent(".dropdown-menu").length&&a.closest("li.dropdown").addClass("active").end().find('[data-toggle="tab"]').attr("aria-expanded",!0);d&&d()}var g=c.find("> .active"),h=d&&b.support.transition&&(g.length&&g.hasClass("fade")||!!c.find("> .fade").length);g.length&&h?g.one("bsTransitionEnd",e).emulateTransitionEnd(f.TRANSITION_DURATION):e();g.removeClass("in")};var e=b.fn.tab;b.fn.tab=h;b.fn.tab.Constructor=f;b.fn.tab.noConflict=function(){b.fn.tab=
e;return this};var g=function(a){a.preventDefault();h.call(b(this),"show")};b(document).on("click.bs.tab.data-api",'[data-toggle="tab"]',g).on("click.bs.tab.data-api",'[data-toggle="pill"]',g)}(jQuery);
+function(b){function h(a){var c;a=a.attr("data-target")||(c=a.attr("href"))&&c.replace(/.*(?=#[^\s]+$)/,"");return b(a)}function f(a){return this.each(function(){var c=b(this),d=c.data("bs.collapse"),f=b.extend({},e.DEFAULTS,c.data(),"object"==typeof a&&a);!d&&f.toggle&&/show|hide/.test(a)&&(f.toggle=!1);d||c.data("bs.collapse",d=new e(this,f));if("string"==typeof a)d[a]()})}var e=function(a,c){this.$element=b(a);this.options=b.extend({},e.DEFAULTS,c);this.$trigger=b('[data-toggle="collapse"][href="#'+
a.id+'"],[data-toggle="collapse"][data-target="#'+a.id+'"]');this.transitioning=null;this.options.parent?this.$parent=this.getParent():this.addAriaAndCollapsedClass(this.$element,this.$trigger);this.options.toggle&&this.toggle()};e.VERSION="3.3.7";e.TRANSITION_DURATION=350;e.DEFAULTS={toggle:!0};e.prototype.dimension=function(){return this.$element.hasClass("width")?"width":"height"};e.prototype.show=function(){if(!this.transitioning&&!this.$element.hasClass("in")){var a,c=this.$parent&&this.$parent.children(".panel").children(".in, .collapsing");
if(c&&c.length&&(a=c.data("bs.collapse"))&&a.transitioning)return;var d=b.Event("show.bs.collapse");this.$element.trigger(d);if(!d.isDefaultPrevented()){c&&c.length&&(f.call(c,"hide"),a||c.data("bs.collapse",null));var g=this.dimension();this.$element.removeClass("collapse").addClass("collapsing")[g](0).attr("aria-expanded",!0);this.$trigger.removeClass("collapsed").attr("aria-expanded",!0);this.transitioning=1;a=function(){this.$element.removeClass("collapsing").addClass("collapse in")[g]("");this.transitioning=
0;this.$element.trigger("shown.bs.collapse")};if(!b.support.transition)return a.call(this);c=b.camelCase(["scroll",g].join("-"));this.$element.one("bsTransitionEnd",b.proxy(a,this)).emulateTransitionEnd(e.TRANSITION_DURATION)[g](this.$element[0][c])}}};e.prototype.hide=function(){if(!this.transitioning&&this.$element.hasClass("in")){var a=b.Event("hide.bs.collapse");this.$element.trigger(a);if(!a.isDefaultPrevented()){a=this.dimension();this.$element[a](this.$element[a]())[0].offsetHeight;this.$element.addClass("collapsing").removeClass("collapse in").attr("aria-expanded",
!1);this.$trigger.addClass("collapsed").attr("aria-expanded",!1);this.transitioning=1;var c=function(){this.transitioning=0;this.$element.removeClass("collapsing").addClass("collapse").trigger("hidden.bs.collapse")};if(!b.support.transition)return c.call(this);this.$element[a](0).one("bsTransitionEnd",b.proxy(c,this)).emulateTransitionEnd(e.TRANSITION_DURATION)}}};e.prototype.toggle=function(){this[this.$element.hasClass("in")?"hide":"show"]()};e.prototype.getParent=function(){return b(this.options.parent).find('[data-toggle="collapse"][data-parent="'+
this.options.parent+'"]').each(b.proxy(function(a,c){var d=b(c);this.addAriaAndCollapsedClass(h(d),d)},this)).end()};e.prototype.addAriaAndCollapsedClass=function(a,b){var c=a.hasClass("in");a.attr("aria-expanded",c);b.toggleClass("collapsed",!c).attr("aria-expanded",c)};var g=b.fn.collapse;b.fn.collapse=f;b.fn.collapse.Constructor=e;b.fn.collapse.noConflict=function(){b.fn.collapse=g;return this};b(document).on("click.bs.collapse.data-api",'[data-toggle="collapse"]',function(a){var c=b(this);c.attr("data-target")||
a.preventDefault();a=h(c);c=a.data("bs.collapse")?"toggle":c.data();f.call(a,c)})}(jQuery);
+function(b){function h(){var b=document.createElement("bootstrap"),e={WebkitTransition:"webkitTransitionEnd",MozTransition:"transitionend",OTransition:"oTransitionEnd otransitionend",transition:"transitionend"},g;for(g in e)if(void 0!==b.style[g])return{end:e[g]};return!1}b.fn.emulateTransitionEnd=function(f){var e=!1,g=this;b(this).one("bsTransitionEnd",function(){e=!0});setTimeout(function(){e||b(g).trigger(b.support.transition.end)},f);return this};b(function(){b.support.transition=h();b.support.transition&&
(b.event.special.bsTransitionEnd={bindType:b.support.transition.end,delegateType:b.support.transition.end,handle:function(f){if(b(f.target).is(this))return f.handleObj.handler.apply(this,arguments)}})})}(jQuery);